import type { User } from "../types";

export const MOCK_USERS: User[] = [
  {
    id: "u1",
    username: "vaultx",
    displayName: "Vault X",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/png?seed=vaultx&size=128",
    bio: "Top 0.1% globally. Aura doesn't lie. 🔮",
    auraScore: 142800,
    level: "LEGENDARY",
    globalRank: 1,
    weeklyRank: 1,
    badges: [
      { id: "b1", label: "LEGENDARY", icon: "👑" },
      { id: "b2", label: "GOAT", icon: "🐐" },
      { id: "b3", label: "1ST PLACE", icon: "🥇" },
    ],
    postCount: 247,
    ratingCount: 18420,
    joinedAt: "2024-01-15",
  },
  {
    id: "u2",
    username: "nova_k",
    displayName: "Nova K",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/png?seed=novak&size=128",
    bio: "Fashion. Aura. Repeat. 💜",
    auraScore: 98400,
    level: "LEGENDARY",
    globalRank: 2,
    weeklyRank: 3,
    badges: [
      { id: "b4", label: "LEGENDARY", icon: "👑" },
      { id: "b5", label: "FASHION ICON", icon: "✨" },
    ],
    postCount: 189,
    ratingCount: 12300,
    joinedAt: "2024-02-03",
  },
  {
    id: "u3",
    username: "ryze_up",
    displayName: "Ryze",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/png?seed=ryzeup&size=128",
    bio: "Pro gamer. Gym rat. Zero filter.",
    auraScore: 67300,
    level: "ELITE",
    globalRank: 5,
    weeklyRank: 2,
    badges: [
      { id: "b6", label: "ELITE", icon: "⚡" },
      { id: "b7", label: "TOP RATER", icon: "🎯" },
    ],
    postCount: 134,
    ratingCount: 8900,
    joinedAt: "2024-03-10",
  },
  {
    id: "u4",
    username: "celestia",
    displayName: "Celestia",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/png?seed=celestia&size=128",
    bio: "streetwear & vibes. DMs closed 🚫",
    auraScore: 52100,
    level: "ELITE",
    globalRank: 9,
    weeklyRank: 7,
    badges: [
      { id: "b8", label: "ELITE", icon: "⚡" },
      { id: "b9", label: "TRENDSETTER", icon: "🔥" },
    ],
    postCount: 98,
    ratingCount: 7200,
    joinedAt: "2024-04-20",
  },
  {
    id: "u5",
    username: "alex",
    displayName: "Alex",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/png?seed=alex123&size=128",
    bio: "Just farming aura one post at a time 🌱",
    auraScore: 9482,
    level: "AURA FARMER",
    globalRank: 184,
    weeklyRank: 47,
    badges: [
      { id: "b10", label: "AURA FARMER", icon: "🌾" },
      { id: "b11", label: "CONSISTENT", icon: "📈" },
    ],
    postCount: 42,
    ratingCount: 2100,
    joinedAt: "2024-06-01",
  },
  {
    id: "u6",
    username: "kira_drops",
    displayName: "Kira",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/png?seed=kiradrops&size=128",
    bio: "music producer. gym. cars. 🎵",
    auraScore: 28700,
    level: "AURA FARMER",
    globalRank: 31,
    weeklyRank: 12,
    badges: [
      { id: "b12", label: "AURA FARMER", icon: "🌾" },
      { id: "b13", label: "MUSICIAN", icon: "🎵" },
    ],
    postCount: 76,
    ratingCount: 5400,
    joinedAt: "2024-05-14",
  },
  {
    id: "u7",
    username: "jett99",
    displayName: "Jett",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/png?seed=jett99&size=128",
    bio: "speedrunning the leaderboard 💨",
    auraScore: 7800,
    level: "RISING",
    globalRank: 241,
    weeklyRank: 58,
    badges: [{ id: "b14", label: "RISING", icon: "📈" }],
    postCount: 28,
    ratingCount: 980,
    joinedAt: "2024-08-22",
  },
  {
    id: "u8",
    username: "mxne",
    displayName: "MXNE",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/png?seed=mxne&size=128",
    bio: "cars and drip only ⚡🚗",
    auraScore: 5200,
    level: "RISING",
    globalRank: 392,
    weeklyRank: 88,
    badges: [{ id: "b15", label: "RISING", icon: "📈" }],
    postCount: 19,
    ratingCount: 640,
    joinedAt: "2024-09-05",
  },
  {
    id: "u9",
    username: "taro_w",
    displayName: "Taro",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/png?seed=tarow&size=128",
    bio: "figuring this out 👀",
    auraScore: 1840,
    level: "ROOKIE",
    globalRank: 1847,
    weeklyRank: 420,
    badges: [{ id: "b16", label: "ROOKIE", icon: "🌱" }],
    postCount: 8,
    ratingCount: 210,
    joinedAt: "2024-10-30",
  },
  {
    id: "u10",
    username: "ghost_z",
    displayName: "Ghost",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/png?seed=ghostz&size=128",
    bio: "lurking",
    auraScore: 320,
    level: "NPC",
    globalRank: 12400,
    weeklyRank: 3200,
    badges: [],
    postCount: 2,
    ratingCount: 14,
    joinedAt: "2024-11-20",
  },
];

export const CURRENT_USER = MOCK_USERS[4]; // alex — the "logged in" user
